[package]
name = "jack_threading"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = {version = "1.0", features = ["rt", "rt-multi-thread", "macros", "sync", "time"] }
jack = "0.13"
thiserror = "2"


